# 服务器配置
server:
  port: 8000

# 基础配置
spring:
  application:
    name: fast-pan-server  # 应用名称
  profiles:
    active: dev           # 激活的配置文件，如dev、test、prod


# 数据库配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/fast_pan?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      idle-timeout: 30000
#      pool-name: HikariCP

  # 文件上传配置
  servlet:
    multipart:
          enabled: true
          max-file-size: 4096MB
          max-request-size: 4096MB

  # Redis配置
  data:
    redis:
      client-name:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0




# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mappers/**/*.xml
#  type-aliases-package: com.indiegeeker.pan.server.modules.*.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0




# 日志配置
logging:
  level:
    root: info
    com.indiegeeker.pan: debug
  file:
    name: logs/fast-pan-server.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"


# 安全配置
jwt:
  secret: your-secret-key
  expiration: 86400000  # 24小时
  header: Authorization
  prefix: Bearer

# 自定义业务配置




# SpringDoc/Swagger配置
# @see framework/springdoc/src/main/resources/application.yaml


# 跨域配置
# @see framework/web/src/main/java/com/indiegeeker/pan/web/cors/CorsFilter.java
# spring:
#   mvc:
#     cors:
#       allowed-origins: "*"
#       allowed-methods: GET,POST,PUT,DELETE
#       allowed-headers: "*"
#       max-age: 3600